### ISSUE TITLE
Images are not loading properly

### ISSUE THREAD

**Issue by rohanbari** [danielcranney/rate-my-film#3]
**There are some issues with the current release:**

  1. In Ubuntu 20.04.1 LTS, the first two options in all steps constantly fail to load the Green and Yellow colors.
![image_failed_to_load](https://user-images.githubusercontent.com/54104015/113326045-d1a99100-9336-11eb-8e11-4065ce895996.png)

  2. On the last page, some images are randomly failing to load (i.e. sometimes it does not).
![randomly_failing_to_load](https://user-images.githubusercontent.com/54104015/113327399-86907d80-9338-11eb-9fe4-eb1d01c4581b.png)

**Post Script:**
  1. All the dependencies are correctly installed using `npm install` in the parent directory.
  2. The repository as-it-is cloned using `git clone` without making any changes except installing node modules.

**Comment by danielcranney** [comment]
Thanks for pointing this out Rohan! I'll be sure to take a look at this and see if I can figure out why. Thanks!
